### ISSUE TITLE
Error unclosed action

### ISSUE THREAD

**Issue by AceSyntax** [arttor/helmify#11]
Hi,
I'm very impressed with helmify, saving me a lot of work, thank you!

One problem...
PS C:\dev\Helm\Helmify\One> helm install firstheml  mychart
Error: parse error at (mychart/templates/mongodb-configmap.yaml:8): unclosed action

that file looks like this
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mychart.fullname" . }}-mongodb-secret
  labels:
  {{- include "mychart.labels" . | nindent 4 }}
data:
  mongo-root-password: {{ required "mongodbSecret.mongoRootPassword is required"  .Values.mongodbSecret.mongoRootPassword | b64enc | quote }}
  mongo-root-username: {{ required "mongodbSecret.mongoRootUsername is required"  .Values.mongodbSecret.mongoRootUsername | b64enc | quote }}

the .Values file contains
mongodbSecret:
  mongoRootPassword: ""
  mongoRootUsername: ""

All help much appreciated

Doug

**Comment by AceSyntax** [comment]
My Helm version...

PS C:\dev\Helm\Helmify\One> helm version
version.BuildInfo{Version:"v3.2.3", GitCommit:"8f832046e258e2cb800894579b1b3b50c2d83492", GitTreeState:"clean", GoVersion:"go1.13.12"}

**Comment by jek-bao-choo** [comment]
I could reproduce the error of unclosed action with helm version 3.5 and below. While helm version 3.6 and above do not have this problem. FYI. No action required to fix this has this is a helm version issue.
