### ISSUE TITLE
allow to control CRDs installation

### ISSUE THREAD

**Issue by zig** [arttor/helmify#113]
It would be useful to generate a template for CRDs that allow them to be installed or not, depending on a value ("enabled")

Indeed, if one plan to install several instances of the chart (in different namespaces or not) , the CRDs can only be installed once as they are cluster wide (their name does not depend on the release name).

**Comment by luisdavim** [comment]
I think this is an important one.

**Comment by arttor** [comment]
@zig please try to generate chart with `helmify -crd-dir` [option](https://github.com/arttor/helmify#available-options). It will place CRDs in a separate dir and allow to use Helm's [CRDs options](https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#method-1-let-helm-do-it-for-you) like `--skip-crds`. Does it solve the issue?

**Comment by zig** [comment]
I see, I didn't see this option. And I did not know about this --skip-crds option in helm. That's very interesting, thanks. This should do the job :)
