### ISSUE TITLE
Ingress backend service name not being prefixed with xx.fullname and service name is being changed incorrectly

### ISSUE THREAD

**Issue by AceSyntax** [arttor/helmify#13]
apiVersion: v1
kind: Service
metadata:
  name: firelymongo-service  
  namespace: xxx
spec: 
  selector:
    pod-Label: my-pod
  ports:  
  - protocol: TCP
    port: 4080  
    targetPort: 4080

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: firelyapi-ingress  
  namespace: xxx 
  annotations: 
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - host: dev.local.xyz.com
    http:
      paths:
      - backend:
          service: 
              name: firelymongo-service
              port: 
                number: 4080                    
        path: /firelyapi(/|$)(.*)
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - dev.local.xyz.com

The service is named as 'firelymongo-service', but the file generated for it is called just mongo-service.yaml.   In that file...
apiVersion: v1
kind: Service
metadata:
  name: {{ include "ft.fullname" . }}-mongo-service
  labels:
  {{- include "ft.labels" . | nindent 4 }}

the service has it's 'firely' part removed which is wrong I believe.

The api-ingress.yaml that is generated is...

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "ft.fullname" . }}-api-ingress
  labels:
  {{- include "ft.labels" . | nindent 4 }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - host: dev.local.elektaplatform.com
    http:
      paths:
      - backend:
          service:
            name: firelymongo-service
            port:
              number: 4080
        path: /firelyapi(/|$)(.*)
        pathType: ImplementationSpecific
  tls:
  - hosts:
    - dev.local.elektaplatform.com

Note:- the name: is 'firelymongo-service.'   There is no fullname template here. so I'm having to manually change it to ...
name: {{ include "ft.fullname" . }}-mongo-service
which works fine.
I'm using powershell  Get-content firelyServer-WithMongo.yaml | helmify ft

So  part of the service name being removed and the file that is generated also has that part removed (this isn't critical but seems strange)
Also the ingress name is not being templated, which is causing an issue.

Or am I missing something?

**Comment by arttor** [comment]
Thanks for the feedback! Unfortunately, there is no `Ingress` converter in helmify for now. [Here is the list of supported resources](https://github.com/arttor/helmify#status). I will add `Ingress` this week.

**Comment by AceSyntax** [comment]
OK, thanks.

**Comment by arttor** [comment]
@AceSyntax fixed in [v0.3.4 release](https://github.com/arttor/helmify/releases/tag/v0.3.4)
