### ISSUE TITLE
Broken image repository/tag format in v0.4.9?

### ISSUE THREAD

**Issue by ssmirr** [arttor/helmify#130]
Using latest version of helmify 0.4.9 we are seeing the change below in image. I believe this is not valid, could be a bug?

```diff
    image:
-      repository: localhost:6001/my_project
-      tag: latest
+     repository: localhost
+     tag: 6001/my_project:latest
```

Confirmed 0.4.8 changes it back to what we had

**Comment by arttor** [comment]
Fixed in [909d091dd6771aee63b43a9df16c22bdc883ffb9](https://github.com/arttor/helmify/commit/909d091dd6771aee63b43a9df16c22bdc883ffb9). Will do 0.4.10 release in a minute

**Comment by arttor** [comment]
@ssmirr please try with [v0.4.10](https://github.com/arttor/helmify/releases/tag/v0.4.10) and let me know if it is still reproducible

**Comment by ssmirr** [comment]
Appreciate the quick fix @arttor! 🙏 
Tried v0.4.10 and that issue is fixed now.
