### ISSUE TITLE
Repetitive TemplateName

### ISSUE THREAD

**Issue by chriskery** [arttor/helmify#138]
The source yaml is :
```shell
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myapp
  name: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: proxy-sidecar
          args:
            - --secure-listen-address=0.0.0.0:8443
            - --v=10
          image: gcr.io/kubebuilder/kube-rbac-proxy:v0.8.0
          ports:
            - containerPort: 8443
              name: https
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: myapp
  name: myapp
spec:
  ports:
    - name: https
      port: 8443
      targetPort: https
  selector:
    app: myapp
```

The resulting Helm template is:
```
·> cat test_data/sample-app.yaml| go run ./cmd/helmify myapp
git:(chartname) 
cyw@B-Q6U5MD6R-2311:s005->/Users/cyw/GolandProjects/helmify (0)
·> helm template myapp myapp --debug     
---
# Source: myapp/templates/myapp.yaml
apiVersion: v1
kind: Service
metadata:
  name: myapp-myapp
---
# Source: myapp/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-myapp
```

I wonder if it is always ok to force ```nameTeml = '{{include "%s.fullname".}}-%s'`` for every objName. Normally I would expect ObjName to remain the same if I changed tthe source o Helm Chart, Especially if my chart name is the same as my obj name.

**Comment by arttor** [comment]
This approach allows having multiple releases in the same namespace. Helmify tries to follow Helm best practices so this behaviour was copied from default helm chart generated by `helm create` command.

**Comment by chriskery** [comment]
> This approach allows having multiple releases in the same namespace. Helmify tries to follow Helm best practices so this behaviour was copied from default helm chart generated by `helm create` command.

Thanks for your replying.  But the scenario using Helmify is not the same as a scenario using `helm create`.  When we used Helmify, we had the original yaml file, no matter where I specify helmify's output, I should expect the application deployed to be the same as the one deployed using the original yaml file.

But if we specify ```nameTeml = '{{include "%s.fullname".}}-%s'`, the application deployed with the generated helm chart will be different from the original yaml file. 

Perhaps this should at least be an option for the user to decide if they want to change the ObjName ？

**Comment by arttor** [comment]
understood. I still think that name prefix `'{{include "%s.fullname".}}'` is necessary because Helm release should be in resource name. We can have an option to just use `'{{include "%s.fullname".}}'` instead of `'{{include "%s.fullname".}}-%s'` but in this case we will have conflict if there are multiple deployments or services in the chart.

**Comment by chriskery** [comment]
I'm sorry, I may have had a problem with the way I expressed it. What I mean is whether it is possible to provide an option to use theResourceName in the original yaml file without adding the prefix of chart, not just '{{include "%s.fullname".}}'. In the original yaml file, there will not be two identical deploy files with the same ResourceName under the same namespace.

**Comment by arttor** [comment]
I think we can add such option if it will not change default behaviour. I don't have capacity to implement it right now, but i can help with review if someone volunteers implementing it.
