### ISSUE TITLE
Creating Resources in multiple namespace

### ISSUE THREAD

**Issue by suvaanshkumar** [arttor/helmify#143]
**Issue**: Helmify does not support a list of Yaml files with multiple namespace
Situation: When I have a list of  kubernetes resources in yaml and all of them have specific namespaces for them and the total number of unique namespaces is more than 1. When I use `helmify`  to generate helm charts, I don't get any namespace in metadata for any resources.

**Expectation**:
In the helm chart generated, We get the namespace in the metadata in the chart/templates/yaml file.

**Steps to Reproduce** :

Step1: We have two yaml files as below-
[nginx-service.txt](https://github.com/arttor/helmify/files/15081171/nginx-service.txt)
[nginx-deployment.txt](https://github.com/arttor/helmify/files/15081172/nginx-deployment.txt)
Please Note: The extension of the above have been changed to txt because yaml is not yet supported by github.

Step2: helmify -f <path to the folder in which we have these two files> samplechart
And then you will observe the Helm chart created with no namespaces in metadata in templates/nginx-service.yaml and templates/nginx-deployment.yaml

**Comment by arttor** [comment]
true, multi-ns charts are not supported right now. I don't have capacity to implement it right now, but i can help with review if someone volunteers implementing it.

**Comment by suvaanshkumar** [comment]
Hi @arttor ,
Thanks for your response.
I will try to make these changes. Just started with it [here](https://github.com/suvaanshkumar/helmify). Will keep you updated in case I will be able to make this contribution.

**Comment by arttor** [comment]
changes are available in [v0.4.13 release](https://github.com/arttor/helmify/releases/tag/v0.4.13)
