### ISSUE TITLE
Issue when using imagePullSecret (Secret type: kubernetes.io/dockerconfigjson)

### ISSUE THREAD

**Issue by f1tzpatrick** [arttor/helmify#26]
Hello! Hope you are well.

When given a secret of `type: kubernetes.io/dockerconfigjson`, helmify does not preserve the `type` field in the resulting template:

Input:
```
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: foobar-registry-credentials
data:
  .dockerconfigjson: |
    ewogICAgImF1dGhzIjogewogICAgICAgICJmb28uYmFyLmlvIjogewogICAgICAgICAgIC
    AidXNlcm5hbWUiOiAidXNlcm5hbWUiLAogICAgICAgICAgICAicGFzc3dvcmQiOiAic2Vj
    cmV0IiwKICAgICAgICAgICAgImF1dGgiOiAiZFhObGNtNWhiV1U2YzJWamNtVjAiCiAgIC
    AgICAgfQogICAgfQp9
```

Output:
```
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "foobar.fullname" . }}-registry-credentials
  labels:
  {{- include "foobar.labels" . | nindent 4 }}
data:
  .dockerconfigjson: {{ required "registryCredentials.dockerconfigjson is required"
    .Values.registryCredentials.dockerconfigjson | b64enc | quote }}
```

I looked around the code and it seems like I might be able to simply add a field for type [here](https://github.com/arttor/helmify/blob/main/pkg/processor/secret/secret.go#L20) and [here](https://github.com/arttor/helmify/blob/main/pkg/processor/secret/secret.go#L112). I will try to get something working and will make a PR if I'm successful.

Also (maybe unrelated issue) - I am using kustomize to add the 'foobar' name prefix. Helmify properly added `{{ include "foobar.fullname" . }}` to my Secret's name, however in my deployment spec, I just see 'foobar' 

```
...
spec:
  template:
    spec:
      ...
      imagePullSecrets:
      - name: foobar-registry-credentials
```

**Comment by f1tzpatrick** [comment]
So far I've been able to get the type output as desired. I think I can handle `imagePullSecrets` naming in [`pkg/processor/deployment/deployment.go`](https://github.com/arttor/helmify/blob/main/pkg/processor/deployment/deployment.go#L198)  as well. Will update soon

**Comment by arttor** [comment]
@f1tzpatrick thank you for your contribution! Created [v0.3.8 release](https://github.com/arttor/helmify/releases/tag/v0.3.8) for your fix.

**Comment by f1tzpatrick** [comment]
Thank you!
