### ISSUE TITLE
generate multiline configmap

### ISSUE THREAD

**Issue by navi86** [arttor/helmify#30]
I am trying to generate helm chart from yaml file https://github.com/Altinity/clickhouse-operator/blob/master/deploy/operator/clickhouse-operator-install-bundle.yaml
but it creates variables with all multiline code as one variable:
`
 defaultPodTemplateYamlExample: | 

    apiVersion: "clickhouse.altinity.com/v1"
    kind: "ClickHouseInstallationTemplate"
    metadata:
      name: "default-oneperhost-pod-template"
    spec:
      templates:
        podTemplates: 
          - name: default-oneperhost-pod-template
            distribution: "OnePerHost"
`
do I do something wrong or is it a what should I expect of using helmify ?

**Comment by arttor** [comment]
@navi86 hope it is not too late. Fixed in [v0.3.31 release](https://github.com/arttor/helmify/releases/tag/v0.3.31)
