### ISSUE TITLE
why helmify doesn't  support Daemonset and Statefulset?

### ISSUE THREAD

**Issue by huangzixun123** [arttor/helmify#31]
Hello, arttor, 
     I think daemonset and statefulset are frequently-used resource，and  why helmify doesn't  support Daemonset and Statefulset?
The support for statefulset and daemonset are on plan?

**Comment by arttor** [comment]
Hi, very good question. It is definitely in the plan. 
There is [PR to support Statefulset](https://github.com/arttor/helmify/pull/29) and I will merge it after the requested changes will be made. 
For the daemonset, please create PR or an issue.

**Comment by huangzixun123** [comment]
这是来自QQ邮箱的自动回复邮件。
您好，已收到您的邮件~~谢谢

**Comment by huangzixun123** [comment]
> 

Thanks for replying, and i will create PR for daemonset when i am free.

**Comment by huangzixun123** [comment]
> Hi, very good question. It is definitely in the plan. There is [PR to support Statefulset](https://github.com/arttor/helmify/pull/29) and I will merge it after the requested changes will be made. For the daemonset, please create PR or an issue.

Thanks for your replying, and i will create PR for daemonset when i  have time.
