### ISSUE TITLE
put any CRD in its own directory

### ISSUE THREAD

**Issue by fire-ant** [arttor/helmify#43]
thanks for making/maintaining this tool, fills a much needed gap in Operator-SDK, appreciated.

per [the latest helm3 docs](https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#method-1-let-helm-do-it-for-you) it would be nice if there was the option to place crds in their own directory so that users can take advantage of any further changes to how CRDs are handled during the install process. I can also see how this would be cleaner and makes using other validation tooling simpler to use by convention.

I haven't written much go but could have a look if its more than 5 minutes for anyone else.

**Comment by arttor** [comment]
@fire-ant very good idea. Definetely woud be cool to have such option.

**Comment by fire-ant** [comment]
this could be put behind an env var or cli flag but I dont think that many users would be broken unless they are doing some weird hardcoding to pull in CRDS.

**Comment by arttor** [comment]
agree but it would be more friendly for existing user to disable it by default. For example, if I update helmify and regenerate kustomize output, I will have two  copies of CRDs:
- old ones in /templates
- new ones in /crd
