### ISSUE TITLE
 nil pointer dereference in conversion webhook 

### ISSUE THREAD

**Issue by stotz89** [arttor/helmify#60]
Having a conversion webhook in a CRD which points to an URL and not to a service will cause a nil pointer deference. The affected code line: https://github.com/arttor/helmify/blob/7205b074d20cf10f0065335a093f58a7b3b10f04/pkg/processor/crd/crd.go#L120

According to k8s docs it can be either a service or an URL: https://kubernetes.io/docs/tasks/extend-kubernetes/custom-resources/custom-resource-definition-versioning/#url

**Comment by arttor** [comment]
@stotz89  thank you for your contribution! Changes are available in [v0.3.19 release](https://github.com/arttor/helmify/releases/tag/v0.3.19)
