### ISSUE TITLE
Allow to specify existing imagePullSecret for podSpec

### ISSUE THREAD

**Issue by gprossliner** [arttor/helmify#62]
It is considered a best practise to include an `imagePullSecrets` field in `values.yaml` so that the consumer of a helm chart can use a private registry, for which a Secret has already been created.

It would be nice if helmify checks if there is anything assigned to the `ImagePullSecrets` field of a PodSpec (which may be part of a Deployment, DaemonSet, ...). If this is set, helmify should continue as-is.

But if the `ImagePullSecret` is not set, helmify should include a `imagePullSecrets` in `values.yaml` and include it in the PodSpec, if it has been set by the user.

What do you think?

**Comment by arttor** [comment]
I think it is a good idea.

**Comment by gprossliner** [comment]
Ok. Thank you for the comment. I can make a PR for further discussion.

**Comment by arttor** [comment]
Please do.

**Comment by gprossliner** [comment]
see #63

**Comment by arttor** [comment]
@gprossliner thank you for your contribution. Your changes are available in [v0.3.20 release](https://github.com/arttor/helmify/releases/tag/v0.3.20).
